### PR TITLE
Added "attach file" functionality to email.php

### LINKED ISSUE #15: Complete "Send" functionality of core feature "Compose Email"
Finish the "Compose Email" core feature by creating a function that sends a drafted email to a specified email address.

### LINKED ISSUE #16: Implement core feature "Include Attachments"
Create the core feature "Include Attachments" to allow users to send various file types in their emails alongside a message.

### PR DESCRIPTION
**Pull request by dep153**
Added the option to attach a selected file while composing an email to send to another user

### CODE REVIEW

**Review by SheltonEllis — APPROVED** [review]
Looks Good

**Comment by rishav1325** [comment]
Nice

**Review by spurthib — APPROVED** [review]
Good work!

**Review by rishav1325 — APPROVED** [review]
Nice

**Pull request merged**
